services:
  - type: web
    name: page-pulse
    runtime: python
    repo: https://github.com/Dhruvrawat04/page-pulse-python
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    region: singapore